services:
  postgres:
    container_name: postgres-sql-spring-secapp
    image: postgres:17.5
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
      POSTGRES_DB: spring-secapp
      TZ: Asia/Kolkata   # âœ… correct timezone
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5438:5432"
    restart: unless-stopped

volumes:
  postgres:
